### ISSUE TITLE
get_documents() returns None as the result

### ISSUE THREAD

**Issue by v7t-codes** [psychic-api/psychic-langchain-tutorial#1]
I'm using a notion connector in the tutorial notebook. The same code was working just fine, but now it isn't. I tried removing the connectors and adding a new one. Still no results. 

The only change in the notebook I had to make was, 
`raw_docs = psychic.get_documents(account_id="account_id")
`
instead of 
`raw_docs = psychic.get_documents(connectionId.notion, "account_id" )
`

**Comment by jasonwcfan** [comment]
hey @v7t-codes are you replacing account_id with an actual account_id from dashboard.psychic.dev or the Link modal?

What's the error you're getting?

**Comment by v7t-codes** [comment]
hey @jasonwcfan, I'm replacing it with the actual account_id from the dashboard. The problem is get_document() returns None as the output.

**Comment by jasonwcfan** [comment]
@v7t-codes got it.

Can you try providing both named arguements?:

`raw_docs = psychic.get_documents(account_id="account_id", connector_id=ConnectorId.notion)`

I'll also update the notebook to reflect some recent changes

**Comment by v7t-codes** [comment]
Thank a lot @jasonwcfan!! This seems to solve the issue. Marking it as closed.
